---
title: "vonBertalanffy model for Groupo Tortuguero data"
output: html_notebook
---

I try to fit von Bertelanffy growth curve to observed growth data of greens. 

```{r}

rm(list=ls())
library(jagsUI)
library(tidyverse)
library(lubridate)
library(reshape)
library(bayesplot)
library(ggridges)

save.rds <- TRUE

source("Mancini_Cm_functions.R")

# MCMC.params <- list(   n.chains = 3,
#                        n.samples = 50000,
#                        n.burnin = 30000,
#                        n.thin = 5)

dat.1 <- get.data("data/GTC_20190725_Tomo_v2.csv")

# Lo doesn't have enough (>2) recaptures. 
spp <- c("Cm", "Ei", "In") #unique(dat.1$species)

MCMC.params <- list(n.chains = 3,
                    n.samples = 100000,
                    n.burnin = 60000,
                    n.thin = 5)

```

Find those that were captured more than once: (or better to use more than twice since the dataset is so big?)

```{r}
for (s in 1:length(spp)){
  # remove rows with is.na(CCL) is true:
  dat.1 %>% filter(species == spp[s]) %>%
    filter(!is.na(CCL)) -> dat.2
  
  n.cap.ID <- table(dat.2$ID)
  recap.ID <- data.frame(n.cap.ID[n.cap.ID > 2])
  colnames(recap.ID) <- c("ID", "Freq")
  
  recap.ID %>% left_join(dat.2, by = "ID") -> recap.data
  
  # Make length and capture date matrices
  unique.ID <- recap.ID$ID
  size.mat <- date.mat <- matrix(nrow = length(unique.ID),
                                 ncol = max(recap.data$Freq))
  
  date.1 <- structure(numeric(length(unique.ID)), class = "Date")
  n.vec <- vector(mode = "numeric", length = length(unique.ID))
  
  k <- 1
  for (k in 1:length(unique.ID)){
    tmp.ID <- filter(recap.data, ID == unique.ID[k])
    size.mat[k, 1:nrow(tmp.ID)] <- tmp.ID$CCL
    date.mat[k, 1:nrow(tmp.ID)] <- tmp.ID$DATE - min(tmp.ID$DATE)
    date.1[k] <- min(tmp.ID$DATE)
    n.vec[k] <- nrow(tmp.ID)
  }
  
  date.mat <- date.mat[, 2:ncol(date.mat)]/365
  
  jags.data <- list(nIndiv = length(unique.ID),
                    n = n.vec,
                    L = size.mat,
                    t = date.mat)
  
  MCMC.params$model.file <-  "models/Model_RlinfRk_L.txt"
  if (!file.exists(paste0("RData/Rlinf_Rk_", spp[s], ".rds"))){
    parameters <- c('CV', 'k', 'A', 
                    'Linf', 'LinfMu', 'LinfSD', 
                    'Shape', 'rate', #'kAlpha', 'kBeta', 
                    'deviance')
    jm.1 <- jags(data = jags.data,
               #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
  if(save.rds) saveRDS(jm.1, file = paste0("RData/Rlinf_Rk_", spp[s], ".rds"))
  
  } 

  if (!file.exists(paste0("RData/Rlinf_Fk_", spp[s], ".rds"))){
    MCMC.params$model.file <- "models/Model_Rlinf_Fk.txt"
    parameters <- c('CV', 'k', 'A', 
                    'Linf', 'LinfMu', 'LinfSD', 
                    'Shape', 'rate', #'kAlpha', 'kBeta', 
                    'deviance')
    
    jm.2 <- jags(data = jags.data,
                 #inits = inits,
                 parameters.to.save= parameters,
                 model.file = MCMC.params$model.file,
                 n.chains = MCMC.params$n.chains,
                 n.burnin = MCMC.params$n.burnin,
                 n.thin = MCMC.params$n.thin,
                 n.iter = MCMC.params$n.samples,
                 DIC = T, 
                 parallel=T)
    
    if(save.rds) saveRDS(jm.2, file = paste0("RData/Rlinf_Fk_", spp[s], ".rds"))
    
  } 
  
  if (!file.exists(paste0("RData/Flinf_Fk_", spp[s], ".rds"))){
    MCMC.params$model.file <- "models/Model_Flinf_Fk.txt"
    parameters <- c('CV', 'k', 'A', 
                    'Linf',  
                    'Shape', 'rate', #'kAlpha', 'kBeta', 
                    'deviance')
    
    jm.3 <- jags(data = jags.data,
                 #inits = inits,
               parameters.to.save= parameters,
               model.file = MCMC.params$model.file,
               n.chains = MCMC.params$n.chains,
               n.burnin = MCMC.params$n.burnin,
               n.thin = MCMC.params$n.thin,
               n.iter = MCMC.params$n.samples,
               DIC = T, 
               parallel=T)
  
    if(save.rds) saveRDS(jm.3, file = paste0("RData/Flinf_Fk_", spp[s], ".rds"))
    
  } 
  
  if (!file.exists(paste0("RData/Flinf_Rk_", spp[s], ".rds"))){
    MCMC.params$model.file <- "models/Model_Flinf_Rk.txt"
    parameters <- c('CV', 'k', 'A', 
                    'Linf',  
                    'Shape', 'rate', #'kAlpha', 'kBeta', 
                    'deviance')
    
    jm.4 <- jags(data = jags.data,
                 #inits = inits,
                 parameters.to.save= parameters,
                 model.file = MCMC.params$model.file,
                 n.chains = MCMC.params$n.chains,
                 n.burnin = MCMC.params$n.burnin,
                 n.thin = MCMC.params$n.thin,
                 n.iter = MCMC.params$n.samples,
                 DIC = T, 
                 parallel=T)
    
    if(save.rds) saveRDS(jm.4, file = paste0("RData/Flinf_Rk_", spp[s], ".rds"))
    
  } 
}

```

